### ISSUE TITLE
Open-Sourcing Training Data

### ISSUE THREAD

**Issue by uApiv** [QwenLM/AutoIF#12]
Hi Authors,

Thanks for your amazing work. I'm interested in knowing if there are plans to open-source the fine tuning data.

**Comment by dongguanting** [comment]
Of course, we are currently following the company's open-source process. The paper is under review, and we will release all the training data once the paper is accepted.

**Comment by xypan0** [comment]
Thanks for this great work! We have reimplemented AutoIF with custom modifications. We generated 61K instruction data following AutoIF using gpt4-o-mini and we release our data [here](https://huggingface.co/datasets/Post-training-Data-Flywheel/AutoIF-instruct-61k) and code [here](https://github.com/shizhediao/Post-Training-Data-Flywheel/tree/main/IF-generation). We hope this helps.

**Comment by dongguanting** [comment]
> Thanks for this great work! We have reimplemented AutoIF with custom modifications. We generated 61K instruction data following AutoIF using gpt4-o-mini and we release our data [here](https://huggingface.co/datasets/Post-training-Data-Flywheel/AutoIF-instruct-61k) and code [here](https://github.com/shizhediao/Post-Training-Data-Flywheel/tree/main/IF-generation). We hope this helps.

That is indeed a brilliant piece of work, and we encourage everyone to take a look!
