### ISSUE TITLE
Instruction level dpo?

### ISSUE THREAD

**Issue by cizhenshi** [QwenLM/AutoIF#13]
In your paper, it is mentioned that instruction-level DPO (Direct Preference Optimization) is constructed based on test cases C. I am a bit confused about what the instructions for DPO data look like. For example, if the instruction is "You must answer using a word that starts with the letter B," and the test cases c1 and c2 are "Black" and "Apple," how do these three elements form a pair?

chosen:   query: You must answer using a word that starts with the letter B     answer: Black
rejected:  query: You must answer using a word that starts with the letter B     answer: Apple

like this?

**Comment by dongguanting** [comment]
yes！the dpo data format like [https://github.com/hiyouga/LLaMA-Factory/blob/main/data/dpo_en_demo.json](https://github.com/hiyouga/LLaMA-Factory/blob/main/data/dpo_en_demo.json)
