### ISSUE TITLE
Open access models

### ISSUE THREAD

**Issue by puffy310** [QwenLM/AutoIF#5]
Good afternoon, I am wondering if Open Access models as reported will be released to further help research direction. The finalized dataset would also be a nice way to properly demonstrate the capabilities of this technique. Thank you!

**Comment by dongguanting** [comment]
Thank you for your suggestion! We are actively applying for the company's data open source process. In fact, our open source code can fully reproduce our results, and the reproduction is not complicated.

**Comment by choco9966** [comment]
I think the code RFT.py and verification_funcs_cases_generation.py weren't fully completed. Is it possible to reproduce them?

**Comment by dongguanting** [comment]
Of course you can reproduce. You only need to replace the supervision model (e.g. use Qwen2-72B, gpt4 api) as needed to perform data generation. We have already preprocess the data and concat the prompt template for you. Just follow the article's hyperparameters to reproduce the results.

Here you can found the guidence using Qwen2 for generation:

https://github.com/QwenLM/Qwen2

You can also find GPT-4 and LLaMA 3 on their respective official websites.

**Comment by yuanzhiyong1999** [comment]
@choco9966 May I ask if you have successfully reproduced it?

**Comment by choco9966** [comment]
@yuanzhiyong1999 Probably? It ran successfully, but the performance is not that great. I used Qwen2-72b, but the quality of the responses was not as good as expected. Additionally, there were many packages like NLTK that were included but not used in the middle, and I am not sure how they are integrated.

**Comment by Lukeming-tsinghua** [comment]
We also find many generated validation functions may rely on NLTK. You can try installing the full NLTK and setting related env before parsing all funcs.
