### ISSUE TITLE
Some issues with code

### ISSUE THREAD

**Issue by drdsgvo** [QwenLM/AutoIF#6]
Example: code/4_eval_func_backtranslator.py
back_instruction = json.loads(back_instruction)
--> correct may be
back_instruction = json.loads(instruction)

back_trans.jsonl i empty after running step 4 for the ShareGPT i used.
--> the given link to ShareGPT is not in jsonl. I fixed that by converting

I assume some other issues exist as well.
After step 9, results are there but not very much.

**Comment by dongguanting** [comment]
Thank you for your suggestion, your understanding is correct, we will fix this bug

**Comment by dongguanting** [comment]
> instruction

Sorry that you did not understand it correctly. Code/4_eval_func_backtranslator.py needs to add the code for supervision model back translation, that is, use the supervision model to perform back translation on each instruction and output the result in the back translation variable, as shown in the following figure:

![image](https://github.com/QwenLM/AutoIF/assets/60767110/3cff59de-51bb-4607-8cbb-67f38dbffee4)

I have already spliced ​​the back translate prompt for you in the instruction variable.
