### ISSUE TITLE
Open source dataset  

### ISSUE THREAD

**Issue by yuanzhiyong1999** [QwenLM/AutoIF#8]
It is mentioned in the paper that the SFT and DPO datasets built based on AUTOIF will be open-sourced together with Qwen2-72B. May I ask where they are?

**Comment by yuanzhiyong1999** [comment]
May I ask if each line in seed_instruction.txt and augment_instructions.txt corresponds to each other? Is the data in augment an enhanced version of the corresponding line in seed?
@dongguanting

**Comment by dongguanting** [comment]
> May I ask if each line in seed_instruction.txt and augment_instructions.txt corresponds to each other? Is the data in augment an enhanced version of the corresponding line in seed? @dongguanting

Thank you for your attention, As shown in the prompt example in our RFT.py：

<img width="847" alt="image" src="https://github.com/user-attachments/assets/25cb713e-7cc5-4c58-a9d8-73229c5a673a">

we will have the supervision model directly generate 50 augmented instructions at a time from the seed data, so there is no one-to-one correspondence.
