### ISSUE TITLE
能否提供中文指令的seed instruction示例？

### ISSUE THREAD

**Issue by JJJJerry** [QwenLM/AutoIF#9]
感觉调用的模型对中文指令生成的验证函数效果不好。事实上，用一个普通的函数验证一个中文句子是否遵循某个指令本身也是一件很难的事，想问问是否能提供中文指令的seed instruction示例供参考？万分感谢！

**Comment by dongguanting** [comment]
我们内部有在探索中文部分的指令遵循，确实发现了中英文极大差异，毕竟英文更多是token level而中文大多则是以词语为单位，不过我们暂时没有开源中文指令集的计划唉。
